# docker-compose.yml
version: "3.9"

services:
  db:
    image: postgres:14
    container_name: siirh-db
    environment:
      POSTGRES_USER: siirh_user
      POSTGRES_PASSWORD: Jeremi123
      POSTGRES_DB: siirh
    ports:
      - "5432:5432"
    volumes:
      - siirh_db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: siirh-backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_USER: siirh_user
      DB_PASSWORD: Jeremi123
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: siirh
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend:/app  # ho mora ny debug rehefa manova code

volumes:
  siirh_db_data:
